#ifndef DECISION_TREE_H
#define DECISION_TREE_H

// AUTO-GENERATED BY PYTHON: DO NOT EDIT MANUALLY
inline bool evaluate_model(int f0, int f1, int f2) {
  if (f1 <= 4.5) {
    return false;
  } else {
    return true;
  }
}

#endif
